import "dotenv/config";
import cors from "cors";
import express from "express";
const app=express();app.use(cors());app.use(express.json());
const PORT=process.env.PORT||3000;
const PAIRS=["EURUSD","EURJPY","GBPUSD","USDJPY","XAUUSD","AUDJPY","AUDUSD"];
const TFS=["1m","2m","5m","15m","1h"];
const MODES=["ICT","SMC","PRICE ACTION","STRUCTURE","LIQUIDITY","MOMENTUM","MTF","COMPOSITE"];
const BIQUOTE=new Set(["EURUSD","EURJPY","GBPUSD","USDJPY","AUDJPY","AUDUSD"]);
const SYMBOLS={EURUSD:"EUR/USD",EURJPY:"EUR/JPY",GBPUSD:"GBP/USD",USDJPY:"USD/JPY",AUDJPY:"AUD/JPY",AUDUSD:"AUD/USD",XAUUSD:"XAU/USD"};
function norm(a){return a.map(x=>({time:Number(x.time??new Date(x.openTime).getTime()),open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time)}
function agg(a,m){const s=m*60000,b=new Map();for(const x of a){const k=Math.floor(x.time/s)*s;if(!b.has(k))b.set(k,[]);b.get(k).push(x)}return[...b].map(([time,r])=>({time,open:r[0].open,high:Math.max(...r.map(x=>x.high)),low:Math.min(...r.map(x=>x.low)),close:r.at(-1).close}))}
async function biq(p,t,l){const iv=t==="2m"?"1m":t,u=new URL(`https://biquote.io/api/${p}/ohlc`);u.searchParams.set("interval",iv);u.searchParams.set("limit",String(Math.min(1000,t==="2m"?l*2:l)));const r=await fetch(u,{signal:AbortSignal.timeout(7000)}),j=await r.json();if(!r.ok||!Array.isArray(j?.bars))throw Error("Biquote unavailable");const z=norm(j.bars);return t==="2m"?agg(z,2).slice(-l):z.slice(-l)}
async function td(p,t,l){const k=process.env.TWELVE_DATA_API_KEY;if(!k)throw Error("Twelve Data key not configured");const iv={"1m":"1min","2m":"1min","5m":"5min","15m":"15min","1h":"1h"}[t],u=new URL("https://api.twelvedata.com/time_series");u.searchParams.set("symbol",SYMBOLS[p]);u.searchParams.set("interval",iv);u.searchParams.set("outputsize",String(Math.min(1000,t==="2m"?l*2:l)));u.searchParams.set("timezone","UTC");u.searchParams.set("apikey",k);const j=await(await fetch(u,{signal:AbortSignal.timeout(9000)})).json();if(!Array.isArray(j?.values))throw Error(j?.message||"Twelve Data unavailable");const z=norm(j.values.map(v=>({...v,time:new Date(String(v.datetime).replace(" ","T")+"Z").getTime()})));return t==="2m"?agg(z,2).slice(-l):z.slice(-l)}
async function candles(p,t,l=800){if(BIQUOTE.has(p)){try{return{rows:await biq(p,t,l),source:"BIQUOTE"}}catch{return{rows:await td(p,t,l),source:"TWELVE_DATA_FALLBACK"}}}return{rows:await td(p,t,l),source:"TWELVE_DATA"}}
const avg=a=>a.reduce((s,v)=>s+v,0)/Math.max(1,a.length),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const atr=q=>avg(q.slice(-14).map(c=>c.high-c.low));
function pivots(q,n=2){const h=[],l=[];for(let i=n;i<q.length-n;i++){const w=q.slice(i-n,i+n+1),c=q[i];if(c.high===Math.max(...w.map(x=>x.high)))h.push({i,time:c.time,price:c.high});if(c.low===Math.min(...w.map(x=>x.low)))l.push({i,time:c.time,price:c.low})}return{h,l}}
function baseState(q){const x=q.at(-1),a=atr(q),P=pivots(q,2),ph=P.h.at(-1),pl=P.l.at(-1),ph2=P.h.at(-2),pl2=P.l.at(-2),r=q.slice(-40,-2),hi=Math.max(...q.slice(-120).map(c=>c.high)),lo=Math.min(...q.slice(-120).map(c=>c.low)),eq=(hi+lo)/2,bsl=Math.max(...r.map(c=>c.high)),ssl=Math.min(...r.map(c=>c.low)),fast=avg(q.slice(-8).map(c=>c.close)),slow=avg(q.slice(-21).map(c=>c.close)),mom=x.close-q.at(-6).close,body=Math.abs(x.close-x.open),range=Math.max(1e-12,x.high-x.low);return{x,a,P,ph,pl,ph2,pl2,hi,lo,eq,bsl,ssl,fast,slow,mom,bodyPct:body/range,bullStruct:!!(ph&&ph2&&pl&&pl2&&ph.price>ph2.price&&pl.price>pl2.price),bearStruct:!!(ph&&ph2&&pl&&pl2&&ph.price<ph2.price&&pl.price<pl2.price),sweptHigh:q.slice(-8).some(c=>c.high>bsl&&c.close<bsl),sweptLow:q.slice(-8).some(c=>c.low<ssl&&c.close>ssl)}}
function findArrays(q,s){const fvgs=[],obs=[];for(let i=2;i<q.length;i++){const A=q[i-2],C=q[i];if(C.low>A.high){const low=A.high,high=C.low;if(!q.slice(i+1).some(k=>k.low<=low))fvgs.push({name:"BULL FVG",low,high,startTime:A.time,kind:"FVG",direction:"BUY",ce:(low+high)/2})}if(C.high<A.low){const low=C.high,high=A.low;if(!q.slice(i+1).some(k=>k.high>=high))fvgs.push({name:"BEAR FVG",low,high,startTime:A.time,kind:"FVG",direction:"SELL",ce:(low+high)/2})}}for(let i=1;i<q.length-1;i++){const c=q[i],n=q[i+1],m=n.close-n.open,after=q.slice(i+2);if(c.close<c.open&&m>s.a*.7&&n.close>c.high&&!after.some(k=>k.close<c.low))obs.push({name:"BULL OB",low:c.low,high:c.high,startTime:c.time,kind:"OB",direction:"BUY",ce:(c.low+c.high)/2});if(c.close>c.open&&m<-s.a*.7&&n.close<c.low&&!after.some(k=>k.close>c.high))obs.push({name:"BEAR OB",low:c.low,high:c.high,startTime:c.time,kind:"OB",direction:"SELL",ce:(c.low+c.high)/2})}return{fvgs,obs}}
function actionableLevel(q,s,dir,arrays){const now=s.x.close,maxDist=s.a*2.2,candidates=[...arrays.fvgs,...arrays.obs].filter(z=>z.direction===dir).filter(z=>Math.abs(z.ce-now)<=maxDist).filter(z=>dir==="BUY"?z.low<=now+s.a*.6:z.high>=now-s.a*.6).sort((a,b)=>Math.abs(a.ce-now)-Math.abs(b.ce-now));const best=candidates[0];if(best)return{price:best.ce,zone:best};const swing=dir==="BUY"?(s.pl?.price??s.ssl):(s.ph?.price??s.bsl);if(Number.isFinite(swing)&&Math.abs(swing-now)<=maxDist)return{price:swing,zone:null};return{price:now,zone:null}}
function finalize(mode,q,s,dir,score,why,arrays){const confidence=dir==="WAIT"?50:clamp(Math.round(52+score*4),56,90),act=dir==="WAIT"?{price:s.x.close,zone:null}:actionableLevel(q,s,dir,arrays),entry=act.price,sl=dir==="BUY"?Math.min(s.ssl,s.pl?.price??s.ssl)-s.a*.15:dir==="SELL"?Math.max(s.bsl,s.ph?.price??s.bsl)+s.a*.15:s.x.close;const targets=dir==="BUY"?[s.eq,s.bsl,s.ph?.price,s.hi].filter(v=>Number.isFinite(v)&&v>Math.max(entry,s.x.close)).slice(0,3):dir==="SELL"?[s.eq,s.ssl,s.pl?.price,s.lo].filter(v=>Number.isFinite(v)&&v<Math.min(entry,s.x.close)).slice(0,3):[];const zones=act.zone?[{...act.zone,name:`${dir} ${act.zone.kind}`}]:[];const lines=[{name:"BSL",price:s.bsl,kind:"BSL"},{name:"SSL",price:s.ssl,kind:"SSL"},{name:"EQ",price:s.eq,kind:"EQ"}];if(dir!=="WAIT"){lines.push({name:dir,price:entry,kind:"ENTRY",prediction:true},{name:"INVALIDATION",price:sl,kind:"SL",prediction:true},...targets.map((v,i)=>({name:`TARGET ${i+1}`,price:v,kind:"TP",prediction:true})))}return{mode,bias:dir,confidence,probabilityType:"confluence score, not statistically calibrated probability",narrative:`${mode}: ${dir} ${confidence}%. ${why}`,entry,stopLoss:sl,targets,overlays:{lines,zones}}}
function analyzeMode(q,mode){const s=baseState(q),arrays=findArrays(q,s);let buy=0,sell=0,why=[];if(mode==="ICT"||mode==="SMC"||mode==="COMPOSITE"){if(s.x.close<s.eq)buy+=2;else sell+=2;if(s.sweptLow){buy+=3;why.push("sell-side liquidity raid")}if(s.sweptHigh){sell+=3;why.push("buy-side liquidity raid")}if(s.bullStruct)buy+=2;if(s.bearStruct)sell+=2;if(arrays.fvgs.some(z=>z.direction==="BUY"))buy++;if(arrays.fvgs.some(z=>z.direction==="SELL"))sell++;if(arrays.obs.some(z=>z.direction==="BUY"))buy++;if(arrays.obs.some(z=>z.direction==="SELL"))sell++}
if(mode==="PRICE ACTION"||mode==="COMPOSITE"){if(s.x.close>s.x.open&&s.bodyPct>.55)buy+=2;if(s.x.close<s.x.open&&s.bodyPct>.55)sell+=2;if(s.fast>s.slow)buy++;else sell++;why.push("candle pressure and trend alignment")}
if(mode==="STRUCTURE"||mode==="MTF"||mode==="COMPOSITE"){if(s.bullStruct){buy+=3;why.push("HH/HL structure")}if(s.bearStruct){sell+=3;why.push("LH/LL structure")}if(s.ph&&s.x.close>s.ph.price)buy+=2;if(s.pl&&s.x.close<s.pl.price)sell+=2}
if(mode==="LIQUIDITY"||mode==="COMPOSITE"){if(s.sweptLow)buy+=4;if(s.sweptHigh)sell+=4;why.push("liquidity draw assessed")}
if(mode==="MOMENTUM"||mode==="MTF"||mode==="COMPOSITE"){if(s.mom>s.a*.4)buy+=2;if(s.mom<-s.a*.4)sell+=2;if(s.fast>s.slow)buy+=2;else sell+=2;why.push("momentum/displacement alignment")}
if(mode==="MTF"){const big=avg(q.slice(-60).map(c=>c.close)),small=avg(q.slice(-15).map(c=>c.close));if(small>big)buy+=2;else sell+=2;why.push("higher-window directional context")}
const delta=buy-sell,dir=Math.abs(delta)<2?"WAIT":delta>0?"BUY":"SELL",score=Math.abs(delta);if(!why.length)why.push("mixed evidence");return finalize(mode,q,s,dir,score,[...new Set(why)].join("; "),arrays)}
function falcon(q,p,t){const r=analyzeMode(q,"COMPOSITE");return{pair:p,timeframe:t,bias:r.bias,confidence:r.confidence,structure:r.narrative,entry:r.entry,stopLoss:r.stopLoss,targets:r.targets}}
app.get("/health",(_q,r)=>r.json({status:"ok",service:"Falcon Analysis"}));
app.get("/api/candles",async(q,r)=>{const p=String(q.query.pair||"EURUSD").toUpperCase(),t=String(q.query.timeframe||"5m").toLowerCase();try{const z=await candles(p,t);r.json({pair:p,timeframe:t,source:z.source,candles:z.rows})}catch(e){r.status(503).json({error:e.message})}});
app.get("/api/analysis",async(q,r)=>{const p=String(q.query.pair||"EURUSD").toUpperCase(),t=String(q.query.timeframe||"5m").toLowerCase(),mode=String(q.query.mode||"ICT").toUpperCase();if(!PAIRS.includes(p)||!TFS.includes(t)||!MODES.includes(mode))return r.status(400).json({error:"Unsupported selection"});try{const z=await candles(p,t);r.json({...analyzeMode(z.rows.slice(-320),mode),pair:p,timeframe:t,source:z.source})}catch(e){r.status(503).json({error:e.message,bias:"WAIT"})}});
const page=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover,user-scalable=no"><title>Falcon Analysis</title><script src="https://unpkg.com/lightweight-charts@4.2.3/dist/lightweight-charts.standalone.production.js"></script><style>*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#070b12;color:#eef5ff;font-family:system-ui}body{overflow-y:auto}.w{width:100%;max-width:1180px;margin:auto;padding:10px}.c{background:#0d1420;border:1px solid #1b293b;border-radius:14px;padding:10px;margin:8px 0}.r,.modes,.tools{display:flex;gap:6px;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none}.r::-webkit-scrollbar,.modes::-webkit-scrollbar,.tools::-webkit-scrollbar{display:none}.b,.mini,.mode{flex:0 0 auto;padding:9px 12px;border-radius:10px;border:1px solid #27384f;background:#101a28;color:#c9d5e5;white-space:nowrap}.a,.on{background:#eef5ff!important;color:#07101b!important}.chartShell{height:58vh;min-height:380px;max-height:520px;position:relative;background:#0a111b;border-radius:10px;overflow:hidden}.chart{position:absolute;inset:0}.overlay{position:absolute;inset:0;pointer-events:none;z-index:4}.hud{position:absolute;z-index:6;left:8px;top:7px;max-width:76%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background:#07101bdd;padding:5px 7px;border-radius:6px;font-size:10px}.small{font-size:12px;color:#a9b6c7;line-height:1.5}.buy{color:#35d49a}.sell{color:#ff657a}.wait{color:#f0c36a}.signal{font-size:28px;font-weight:800;margin:4px 0}.g{display:grid;grid-template-columns:1fr 1fr;gap:8px}@media(max-width:700px){.g{grid-template-columns:1fr}.w{padding:8px}.chartShell{height:55vh;min-height:360px}h1{font-size:25px}}</style></head><body><main class="w"><h1>Falcon Analysis</h1><section class="c"><div class="r" id="pairs"></div><div class="r" id="tfs" style="margin-top:7px"></div><div class="modes" id="modes" style="margin-top:7px"></div></section><section class="c"><div class="chartShell" id="shell"><div id="chart" class="chart"></div><canvas id="ov" class="overlay"></canvas><div id="hud" class="hud">Loading…</div></div><div class="tools"><button id="zonesBtn" class="mini on">Zones</button><button id="liqBtn" class="mini on">Liquidity</button><button id="tradeBtn" class="mini on">Trade Map</button><button id="liveBtn" class="mini">Go Live</button></div></section><section class="c"><div id="sig" class="signal wait">WAIT</div><div id="score" class="small"></div><div id="text" class="small"></div><div id="note" class="small"></div></section></main><script>
const P=${JSON.stringify(PAIRS)},T=${JSON.stringify(TFS)},M=${JSON.stringify(MODES)},$=i=>document.getElementById(i);let p='EURUSD',t='5m',mode='ICT',C=[],I=null,zonesOn=true,liqOn=true,tradeOn=true,priceLines=[];const fmt=v=>Number.isFinite(+v)?(+v).toFixed(p.includes('JPY')?3:p==='XAUUSD'?2:5):'—',local=m=>new Date(m).toLocaleString([],{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'});function buttons(id,a,v,set,cls='b'){const el=$(id);el.innerHTML='';a.forEach(x=>{const b=document.createElement('button');b.className=cls+(x===v?' on':'');b.textContent=x;b.onclick=()=>set(x);el.appendChild(b)})}function ctl(){buttons('pairs',P,p,x=>{p=x;ctl();load(true)});buttons('tfs',T,t,x=>{t=x;ctl();load(true)});buttons('modes',M,mode,x=>{mode=x;ctl();load(false)},'mode')}
const chart=LightweightCharts.createChart($('chart'),{layout:{background:{type:'solid',color:'#0a111b'},textColor:'#8f9dad'},grid:{vertLines:{color:'#111c2a'},horzLines:{color:'#111c2a'}},rightPriceScale:{borderColor:'#1b2b3d'},timeScale:{borderColor:'#1b2b3d',rightOffset:10,barSpacing:7,minBarSpacing:2,timeVisible:true,secondsVisible:false},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:false},handleScale:{axisPressedMouseMove:true,mouseWheel:true,pinch:true}}),series=chart.addCandlestickSeries({upColor:'#26d6a0',downColor:'#ff5d73',wickUpColor:'#26d6a0',wickDownColor:'#ff5d73',borderVisible:false});function resize(){const s=$('shell').getBoundingClientRect();chart.applyOptions({width:s.width,height:s.height});const c=$('ov'),d=devicePixelRatio||1;c.width=s.width*d;c.height=s.height*d;c.style.width=s.width+'px';c.style.height=s.height+'px';drawOverlay()}new ResizeObserver(resize).observe($('shell'));
function addLines(){for(const l of priceLines)try{series.removePriceLine(l)}catch{}priceLines=[];for(const l of I?.overlays?.lines||[]){if(l.prediction&&!tradeOn)continue;if(!l.prediction&&!liqOn)continue;const color=l.kind==='ENTRY'?(I.bias==='BUY'?'#35d49a':'#ff657a'):l.kind==='SL'?'#ff526b':l.kind==='TP'?'#37d49a':l.kind==='BSL'?'#ffb15c':l.kind==='SSL'?'#62b7ff':'#8a98aa';priceLines.push(series.createPriceLine({price:l.price,color,lineWidth:l.prediction?2:1,lineStyle:l.prediction?2:3,axisLabelVisible:l.prediction,title:l.prediction?l.name:''}))}}
function drawOverlay(){const cv=$('ov'),ctx=cv.getContext('2d'),d=devicePixelRatio||1;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,cv.width/d,cv.height/d);if(!I||!zonesOn)return;const W=$('shell').clientWidth-72;for(const z of I.overlays?.zones||[]){const sx0=chart.timeScale().timeToCoordinate(Math.floor((z.startTime||C.at(-60)?.time||0)/1000)),y1=series.priceToCoordinate(z.high),y2=series.priceToCoordinate(z.low);if(y1==null||y2==null)continue;const sx=Math.max(8,sx0??8),top=Math.min(y1,y2);ctx.fillStyle=z.kind==='OB'?'rgba(238,174,70,.11)':'rgba(72,140,255,.10)';ctx.fillRect(sx,top,Math.max(12,W-sx),Math.max(3,Math.abs(y2-y1)));ctx.fillStyle=z.kind==='OB'?'#e6bd79':'#8ab8ff';ctx.font='600 9px system-ui';ctx.fillText(z.name,sx+6,top+12)}}chart.timeScale().subscribeVisibleLogicalRangeChange(drawOverlay);chart.subscribeCrosshairMove(v=>{if(v.time){const d=v.seriesData.get(series);if(d)$('hud').textContent=local(Number(v.time)*1000)+' O '+fmt(d.open)+' H '+fmt(d.high)+' L '+fmt(d.low)+' C '+fmt(d.close)}});function tog(id,k){$(id).onclick=()=>{if(k==='z')zonesOn=!zonesOn;if(k==='l')liqOn=!liqOn;if(k==='t')tradeOn=!tradeOn;$(id).classList.toggle('on',k==='z'?zonesOn:k==='l'?liqOn:tradeOn);addLines();drawOverlay()}}tog('zonesBtn','z');tog('liqBtn','l');tog('tradeBtn','t');$('liveBtn').onclick=()=>chart.timeScale().scrollToRealTime();async function load(reset=false){try{const q='?pair='+p+'&timeframe='+t+'&mode='+encodeURIComponent(mode),[c,a]=await Promise.all([fetch('/api/candles?pair='+p+'&timeframe='+t).then(r=>r.json()),fetch('/api/analysis'+q).then(r=>r.json())]);C=c.candles||[];I=a;const range=chart.timeScale().getVisibleLogicalRange();series.setData(C.map(k=>({time:Math.floor(k.time/1000),open:k.open,high:k.high,low:k.low,close:k.close})));addLines();if(reset)chart.timeScale().setVisibleLogicalRange({from:Math.max(0,C.length-70),to:C.length+10});else if(range&&range.to<C.length-3)chart.timeScale().setVisibleLogicalRange(range);$('sig').textContent=a.bias||'WAIT';$('sig').className='signal '+(a.bias==='BUY'?'buy':a.bias==='SELL'?'sell':'wait');$('score').textContent=(a.confidence||50)+'% '+mode+' confluence';$('text').textContent=a.narrative||a.error||'';$('note').textContent=a.probabilityType?'Probability: '+a.probabilityType:'';if(C.length)$('hud').textContent=p+' · '+t.toUpperCase()+' · '+local(C.at(-1).time)+' · '+fmt(C.at(-1).close);setTimeout(drawOverlay,40)}catch(e){$('text').textContent=e.message}}ctl();load(true);setInterval(()=>load(false),30000);</script></body></html>`;
app.get("/",(_q,r)=>r.type("html").send(page));app.listen(PORT,()=>console.log("Falcon Analysis listening on "+PORT));